### ISSUE TITLE
Output renders a bunch of white space in CI

### ISSUE THREAD

**Issue by milesj** [ccbrown/iocraft#43]
This is a weird one. So I have a CLI command that renders a table of data using iocraft. This works locally when running the command, and when running unit tests locally. 

However, in CI, the tests seems to render a bunch of white space and empty lines, probably because it's not a TTY. For example, here's a failing test:

```
thread 'plugin_search::returns_matching_results' panicked at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5:
Unexpected stdout, failed var.contains(Available for query: zig)
├── var: 
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│   
│
└── var as str:






































```

And this is what it looks like when I run the failing test locally:

```
thread 'plugin_search::returns_matching_results' panicked at /Users/miles/.rustup/toolchains/1.83.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5:
Unexpected stdout, failed var.contains(Available for query: zig)
├── var:
│    Search results for: zig
│    Learn more about plugins: https://moonrepo.dev/docs/proto/plugins
│   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│   │ Plugin             Author        Format    Description                          Locator                                                                                                 │
│   │─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────│
│   │ Zig                stk0vrfl0w    TOML      Zig is a general-purpose programming https://raw.githubusercontent.com/stk0vrfl0w/proto-toml-plugins/main/plugins/zig.toml                   │
│   │                                            language and toolchain.                                                                                                                      │
│   │ Zig                konomae       WASM      Zig is a general-purpose programming github://konomae/zig-plugin                                                                             │
│   │                                            language and toolchain.                                                                                                                      │
│   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
│    Find a plugin above that you want to use? Enable it with: proto plugin add [id] [locator]
│
└── var as str:
     Search results for: zig
     Learn more about plugins: https://moonrepo.dev/docs/proto/plugins
    ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
    │ Plugin             Author        Format    Description                          Locator                                                                                                 │
    │─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────│
    │ Zig                stk0vrfl0w    TOML      Zig is a general-purpose programming https://raw.githubusercontent.com/stk0vrfl0w/proto-toml-plugins/main/plugins/zig.toml                   │
    │                                            language and toolchain.                                                                                                                      │
    │ Zig                konomae       WASM      Zig is a general-purpose programming github://konomae/zig-plugin                                                                             │
    │                                            language and toolchain.                                                                                                                      │
    ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
     Find a plugin above that you want to use? Enable it with: proto plugin add [id] [locator]
```

I'm not really sure how to fix this or what's going on. My assumption is that it's a TTY problem, or that maybe the "width of the terminal" is 0, and the canvas maybe renders nothing?

Anyways, this problem only seems to happen to commands that render a table. Maybe too much data? For reference:

Here's the table code: https://github.com/moonrepo/starbase/blob/master/crates/console/src/components/table.rs

And here's a command using the table:  https://github.com/moonrepo/proto/blob/ui/crates/cli/src/commands/plugin/search.rs

And the test case: https://github.com/moonrepo/proto/blob/ui/crates/cli/tests/plugin_search_test.rs#L40

**Comment by ccbrown** [comment]
I'm pretty sure this is because `hooks.use_terminal_size()` is returning a `0` width for your `Container` element in [console/src/components/layout.rs#L15](https://github.com/moonrepo/starbase/blob/b22617c2a404965be0dd2bcec267491e9930fba5/crates/console/src/components/layout.rs#L15).

With a width of zero, the table gets really tall due to wrapping, but then you can't even see it because the canvas is zero width.

It might make sense in this case to define a minimum width?

```rs
let width = hooks.use_terminal_size().0.max(60);
```

Or maybe add a special case for when the returned `width` is zero?

I'll consider whether there's something we can do in iocraft to make this less of a pitfall.

**Comment by milesj** [comment]
Ah yeah nice catch, that part totally slipped my mind. Let me patch that and see what happens.

**Comment by milesj** [comment]
Yeah that did, thanks again.
